# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'SRAmainGUI.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *
from mplwidget import MplWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1145, 877)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.graphWidget = MplWidget(self.centralwidget)
        self.graphWidget.setObjectName(u"graphWidget")
        self.graphWidget.setGeometry(QRect(30, 60, 421, 431))
        self.tableWidget_Soil = QTableWidget(self.centralwidget)
        if (self.tableWidget_Soil.columnCount() < 3):
            self.tableWidget_Soil.setColumnCount(3)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget_Soil.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget_Soil.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget_Soil.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        self.tableWidget_Soil.setObjectName(u"tableWidget_Soil")
        self.tableWidget_Soil.setGeometry(QRect(490, 60, 441, 192))
        self.tableWidget_Soil.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.pushButton_addSoil = QPushButton(self.centralwidget)
        self.pushButton_addSoil.setObjectName(u"pushButton_addSoil")
        self.pushButton_addSoil.setGeometry(QRect(960, 90, 93, 28))
        self.label_SoilProp = QLabel(self.centralwidget)
        self.label_SoilProp.setObjectName(u"label_SoilProp")
        self.label_SoilProp.setGeometry(QRect(500, 30, 101, 16))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_SoilProp.setFont(font)
        self.pushButton_removeSoil = QPushButton(self.centralwidget)
        self.pushButton_removeSoil.setObjectName(u"pushButton_removeSoil")
        self.pushButton_removeSoil.setGeometry(QRect(960, 130, 93, 28))
        self.tableWidget_Profile = QTableWidget(self.centralwidget)
        if (self.tableWidget_Profile.columnCount() < 4):
            self.tableWidget_Profile.setColumnCount(4)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget_Profile.setHorizontalHeaderItem(0, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget_Profile.setHorizontalHeaderItem(1, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget_Profile.setHorizontalHeaderItem(2, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget_Profile.setHorizontalHeaderItem(3, __qtablewidgetitem6)
        self.tableWidget_Profile.setObjectName(u"tableWidget_Profile")
        self.tableWidget_Profile.setGeometry(QRect(490, 300, 441, 192))
        self.tableWidget_Profile.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.label_profileProp = QLabel(self.centralwidget)
        self.label_profileProp.setObjectName(u"label_profileProp")
        self.label_profileProp.setGeometry(QRect(490, 270, 101, 16))
        self.label_profileProp.setFont(font)
        self.pushButton_removeProfile = QPushButton(self.centralwidget)
        self.pushButton_removeProfile.setObjectName(u"pushButton_removeProfile")
        self.pushButton_removeProfile.setGeometry(QRect(960, 400, 93, 28))
        self.pushButton_addProfile = QPushButton(self.centralwidget)
        self.pushButton_addProfile.setObjectName(u"pushButton_addProfile")
        self.pushButton_addProfile.setGeometry(QRect(960, 360, 93, 28))
        self.pushButton_drawProfile = QPushButton(self.centralwidget)
        self.pushButton_drawProfile.setObjectName(u"pushButton_drawProfile")
        self.pushButton_drawProfile.setGeometry(QRect(960, 440, 93, 28))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(490, 520, 55, 16))
        self.label.setFont(font)
        self.lineEdit_bedWeight = QLineEdit(self.centralwidget)
        self.lineEdit_bedWeight.setObjectName(u"lineEdit_bedWeight")
        self.lineEdit_bedWeight.setGeometry(QRect(560, 520, 71, 22))
        self.label_bedUnits = QLabel(self.centralwidget)
        self.label_bedUnits.setObjectName(u"label_bedUnits")
        self.label_bedUnits.setGeometry(QRect(648, 520, 55, 16))
        font1 = QFont()
        font1.setBold(False)
        font1.setWeight(50)
        self.label_bedUnits.setFont(font1)
        self.label_bedUnits.setTextFormat(Qt.MarkdownText)
        self.lineEdit_bedVelocity = QLineEdit(self.centralwidget)
        self.lineEdit_bedVelocity.setObjectName(u"lineEdit_bedVelocity")
        self.lineEdit_bedVelocity.setGeometry(QRect(710, 520, 71, 22))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(790, 520, 55, 16))
        self.label_2.setFont(font1)
        self.graphWidget_TH = MplWidget(self.centralwidget)
        self.graphWidget_TH.setObjectName(u"graphWidget_TH")
        self.graphWidget_TH.setGeometry(QRect(30, 580, 611, 191))
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(30, 550, 1021, 16))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.pushButton_loadTH = QPushButton(self.centralwidget)
        self.pushButton_loadTH.setObjectName(u"pushButton_loadTH")
        self.pushButton_loadTH.setGeometry(QRect(520, 780, 121, 28))
        self.groupBox_output = QGroupBox(self.centralwidget)
        self.groupBox_output.setObjectName(u"groupBox_output")
        self.groupBox_output.setGeometry(QRect(690, 580, 361, 131))
        self.checkBox_outRS = QCheckBox(self.groupBox_output)
        self.checkBox_outRS.setObjectName(u"checkBox_outRS")
        self.checkBox_outRS.setGeometry(QRect(20, 30, 151, 20))
        self.lineEdit_RSDepth = QLineEdit(self.groupBox_output)
        self.lineEdit_RSDepth.setObjectName(u"lineEdit_RSDepth")
        self.lineEdit_RSDepth.setGeometry(QRect(202, 30, 91, 22))
        self.label_3 = QLabel(self.groupBox_output)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(300, 30, 21, 16))
        self.label_3.setFont(font1)
        self.checkBox_outStrain = QCheckBox(self.groupBox_output)
        self.checkBox_outStrain.setObjectName(u"checkBox_outStrain")
        self.checkBox_outStrain.setGeometry(QRect(20, 90, 151, 20))
        self.lineEdit_strainDepth = QLineEdit(self.groupBox_output)
        self.lineEdit_strainDepth.setObjectName(u"lineEdit_strainDepth")
        self.lineEdit_strainDepth.setGeometry(QRect(200, 90, 91, 22))
        self.label_4 = QLabel(self.groupBox_output)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(300, 90, 21, 16))
        self.label_4.setFont(font1)
        self.checkBox_outAcc = QCheckBox(self.groupBox_output)
        self.checkBox_outAcc.setObjectName(u"checkBox_outAcc")
        self.checkBox_outAcc.setGeometry(QRect(20, 60, 151, 20))
        self.lineEdit_accDepth = QLineEdit(self.groupBox_output)
        self.lineEdit_accDepth.setObjectName(u"lineEdit_accDepth")
        self.lineEdit_accDepth.setGeometry(QRect(202, 60, 91, 22))
        self.label_5 = QLabel(self.groupBox_output)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(300, 60, 21, 16))
        self.label_5.setFont(font1)
        self.pushButton_run = QPushButton(self.centralwidget)
        self.pushButton_run.setObjectName(u"pushButton_run")
        self.pushButton_run.setGeometry(QRect(910, 760, 121, 28))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 780, 51, 16))
        self.label_7.setFont(font1)
        self.lineEdit_FS = QLineEdit(self.centralwidget)
        self.lineEdit_FS.setObjectName(u"lineEdit_FS")
        self.lineEdit_FS.setGeometry(QRect(80, 780, 113, 22))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(230, 780, 31, 16))
        self.label_8.setFont(font1)
        self.comboBox_Units = QComboBox(self.centralwidget)
        self.comboBox_Units.addItem("")
        self.comboBox_Units.addItem("")
        self.comboBox_Units.addItem("")
        self.comboBox_Units.setObjectName(u"comboBox_Units")
        self.comboBox_Units.setGeometry(QRect(290, 780, 91, 22))
        self.lineEdit_maxFreq = QLineEdit(self.centralwidget)
        self.lineEdit_maxFreq.setObjectName(u"lineEdit_maxFreq")
        self.lineEdit_maxFreq.setGeometry(QRect(160, 500, 71, 22))
        self.lineEdit_waveLength = QLineEdit(self.centralwidget)
        self.lineEdit_waveLength.setObjectName(u"lineEdit_waveLength")
        self.lineEdit_waveLength.setGeometry(QRect(160, 530, 71, 22))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(30, 500, 121, 16))
        self.label_9.setFont(font1)
        self.checkBox_autoDiscretize = QCheckBox(self.centralwidget)
        self.checkBox_autoDiscretize.setObjectName(u"checkBox_autoDiscretize")
        self.checkBox_autoDiscretize.setGeometry(QRect(270, 520, 111, 20))
        self.checkBox_autoDiscretize.setChecked(True)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(30, 530, 121, 16))
        self.label_10.setFont(font1)
        self.lineEdit_bedDamping = QLineEdit(self.centralwidget)
        self.lineEdit_bedDamping.setObjectName(u"lineEdit_bedDamping")
        self.lineEdit_bedDamping.setGeometry(QRect(850, 520, 71, 22))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(928, 520, 55, 16))
        self.label_6.setFont(font1)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(690, 730, 121, 16))
        self.label_11.setFont(font1)
        self.lineEdit_strainRatio = QLineEdit(self.centralwidget)
        self.lineEdit_strainRatio.setObjectName(u"lineEdit_strainRatio")
        self.lineEdit_strainRatio.setGeometry(QRect(830, 730, 61, 22))
        self.lineEdit_maxIter = QLineEdit(self.centralwidget)
        self.lineEdit_maxIter.setObjectName(u"lineEdit_maxIter")
        self.lineEdit_maxIter.setGeometry(QRect(830, 760, 61, 22))
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(690, 760, 121, 16))
        self.label_12.setFont(font1)
        self.lineEdit_maxTol = QLineEdit(self.centralwidget)
        self.lineEdit_maxTol.setObjectName(u"lineEdit_maxTol")
        self.lineEdit_maxTol.setGeometry(QRect(830, 790, 61, 22))
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(690, 790, 121, 16))
        self.label_13.setFont(font1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1145, 26))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Prisencolinensinainciu-Soil", None))
        ___qtablewidgetitem = self.tableWidget_Soil.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Name", None));
        ___qtablewidgetitem1 = self.tableWidget_Soil.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Unit Weight", None));
        ___qtablewidgetitem2 = self.tableWidget_Soil.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Degradation curve", None));
        self.pushButton_addSoil.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.label_SoilProp.setText(QCoreApplication.translate("MainWindow", u"Soil properties", None))
        self.pushButton_removeSoil.setText(QCoreApplication.translate("MainWindow", u"-", None))
        ___qtablewidgetitem3 = self.tableWidget_Profile.horizontalHeaderItem(0)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Depth [m]", None));
        ___qtablewidgetitem4 = self.tableWidget_Profile.horizontalHeaderItem(1)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Thickness [m]", None));
        ___qtablewidgetitem5 = self.tableWidget_Profile.horizontalHeaderItem(2)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Soil type", None));
        ___qtablewidgetitem6 = self.tableWidget_Profile.horizontalHeaderItem(3)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"Vs [m/s]", None));
        self.label_profileProp.setText(QCoreApplication.translate("MainWindow", u"Profile", None))
        self.pushButton_removeProfile.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.pushButton_addProfile.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.pushButton_drawProfile.setText(QCoreApplication.translate("MainWindow", u"Draw profile", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Bedrock", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_bedWeight.setToolTip(QCoreApplication.translate("MainWindow", u"Bedrock unit weight", None))
#endif // QT_CONFIG(tooltip)
        self.lineEdit_bedWeight.setText(QCoreApplication.translate("MainWindow", u"22", None))
        self.label_bedUnits.setText(QCoreApplication.translate("MainWindow", u"KN/m<sup>3</sup>", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_bedVelocity.setToolTip(QCoreApplication.translate("MainWindow", u"Bedrock velocity", None))
#endif // QT_CONFIG(tooltip)
        self.lineEdit_bedVelocity.setText(QCoreApplication.translate("MainWindow", u"800", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"m/s", None))
        self.pushButton_loadTH.setText(QCoreApplication.translate("MainWindow", u"Load time history", None))
        self.groupBox_output.setTitle(QCoreApplication.translate("MainWindow", u"Output", None))
        self.checkBox_outRS.setText(QCoreApplication.translate("MainWindow", u"Response spectrum", None))
        self.lineEdit_RSDepth.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"m", None))
        self.checkBox_outStrain.setText(QCoreApplication.translate("MainWindow", u"Strain time history", None))
        self.lineEdit_strainDepth.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"m", None))
        self.checkBox_outAcc.setText(QCoreApplication.translate("MainWindow", u"Acceleration", None))
        self.lineEdit_accDepth.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"m", None))
        self.pushButton_run.setText(QCoreApplication.translate("MainWindow", u"Run analysis", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"FS [Hz]", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_FS.setToolTip(QCoreApplication.translate("MainWindow", u"If specified in input file, sample frequency will be automatically imported from input file", None))
#endif // QT_CONFIG(tooltip)
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Units", None))
        self.comboBox_Units.setItemText(0, QCoreApplication.translate("MainWindow", u"g", None))
        self.comboBox_Units.setItemText(1, QCoreApplication.translate("MainWindow", u"cm/s^2", None))
        self.comboBox_Units.setItemText(2, QCoreApplication.translate("MainWindow", u"m/s^2", None))

        self.lineEdit_maxFreq.setText(QCoreApplication.translate("MainWindow", u"20", None))
        self.lineEdit_waveLength.setText(QCoreApplication.translate("MainWindow", u"0.2", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Max frequency [Hz]", None))
        self.checkBox_autoDiscretize.setText(QCoreApplication.translate("MainWindow", u"Auto discretize", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Wavelength ratio", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_bedDamping.setToolTip(QCoreApplication.translate("MainWindow", u"Bedrock damping", None))
#endif // QT_CONFIG(tooltip)
        self.lineEdit_bedDamping.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Effective strain ratio", None))
        self.lineEdit_strainRatio.setText(QCoreApplication.translate("MainWindow", u"0.65", None))
        self.lineEdit_maxIter.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Max iterations", None))
        self.lineEdit_maxTol.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Error tolerance [%]", None))
    # retranslateUi

